services:
  nginx:
    image: "nginx:1.25-alpine"
    container_name: nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/log:/app/www/estate/logs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    ports:
      - "443:443"
      - "8080:8080"
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - tomcat

  tomcat:
    build: .
    image: resume
    container_name: tomcat
    restart: always
    env_file:
      - .env
    expose:
      - 8080
    #    ports:
    #      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql


  mysql:
    image: "mysql:8.0.43"
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
    expose:
      - 3306

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email platovdima6@gmail.com --agree-tos --no-eff-email -d platovd.ru
    depends_on:
      - nginx


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:


