services:
  tomcat:
    build: .
    image: resume
    container_name: tomcat
    restart: always
    env_file:
      - .env
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql


  mysql:
    image: "mysql:8.0.43"
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:


